### ISSUE TITLE
Spatna dokumentace - nejde podle ni zadat kontejnery do HA

### ISSUE THREAD

**Issue by pschonmann** [Cmajda/ha_golemio#10]
Ahoj, snazim se zadat konťasy do HA, ale nedari se mi podle dokumentace pridat. Chyba bude nekde v configuration.yaml

Zkousim podle navodu  pridat 4 mista

```
# Loads default set of integrations. Do not remove.
default_config:

- platform: golemio
  name: "tk_zelenenecska"
  token: !secret golemio
  container_id: 652
- platform: golemio
  name: "tk_smermetro"
  token: !secret golemio
  container_id: 694
- platform: golemio
  name: "tk_umetra"
  token: !secret golemio
  container_id: 709
- platform: golemio
  name: "tk_umateje"
  token: !secret golemio
  container_id: 709
```
Dostavam hlasku co se vztahuje k default_configu, ze nepodporuje parametry. Podle me tam chybi v yamlu golemio: ktere by specifikovalo ze se jedna o blok golemio
```
Logger: homeassistant.helpers.config_validation
Source: helpers/config_validation.py:1112
First occurred: 12:28:51 PM (1 occurrences)
Last logged: 12:28:51 PM

The default_config integration does not support any configuration parameters, got [{'platform': 'golemio', 'name': 'tk_zelenenecska', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM1OSwiaWF0IjoxNzA0NzA5OTEwLCJleHAiOjExNzA0NzA5OTEwLCJpc3MiOiJnb2xlbWlvIiwianRpIjoiZjVkZDAzZjUtYTFlOS00ZTFkLTkwZjMtMDAzYzE5YTdmMzA0In0.3Jfrz2PT0U0FOPkiXmpu8hJXgX_bMmgd83roTrxqpP0', 'container_id': 652}, {'platform': 'golemio', 'name': 'tk_smermetro', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM1OSwiaWF0IjoxNzA0NzA5OTEwLCJleHAiOjExNzA0NzA5OTEwLCJpc3MiOiJnb2xlbWlvIiwianRpIjoiZjVkZDAzZjUtYTFlOS00ZTFkLTkwZjMtMDAzYzE5YTdmMzA0In0.3Jfrz2PT0U0FOPkiXmpu8hJXgX_bMmgd83roTrxqpP0', 'container_id': 694}, {'platform': 'golemio', 'name': 'tk_umetra', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM1OSwiaWF0IjoxNzA0NzA5OTEwLCJleHAiOjExNzA0NzA5OTEwLCJpc3MiOiJnb2xlbWlvIiwianRpIjoiZjVkZDAzZjUtYTFlOS00ZTFkLTkwZjMtMDAzYzE5YTdmMzA0In0.3Jfrz2PT0U0FOPkiXmpu8hJXgX_bMmgd83roTrxqpP0', 'container_id': 709}, {'platform': 'golemio', 'name': 'tk_umateje', 'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjM1OSwiaWF0IjoxNzA0NzA5OTEwLCJleHAiOjExNzA0NzA5OTEwLCJpc3MiOiJnb2xlbWlvIiwianRpIjoiZjVkZDAzZjUtYTFlOS00ZTFkLTkwZjMtMDAzYzE5YTdmMzA0In0.3Jfrz2PT0U0FOPkiXmpu8hJXgX_bMmgd83roTrxqpP0', 'container_id': 709}]. Please remove the configuration parameters from your configuration.
```

Zkusil jsem to tedy
```
# Loads default set of integrations. Do not remove.
default_config:

golemio:
- platform: golemio
  name: "tk_zelenenecska"
  token: !secret golemio
  container_id: 652
- platform: golemio
  name: "tk_smermetro"
  token: !secret golemio
  container_id: 694
- platform: golemio
  name: "tk_umetra"
  token: !secret golemio
  container_id: 709
- platform: golemio
  name: "tk_umateje"
  token: !secret golemio
  container_id: 709
```
Dostavam chyby
```
Logger: homeassistant.setup
Source: setup.py:279
First occurred: 12:34:17 PM (1 occurrences)
Last logged: 12:34:17 PM

The 'golemio' integration does not support YAML setup, please remove it from your configuration

Logger: homeassistant.setup
Source: setup.py:221
First occurred: 12:34:17 PM (1 occurrences)
Last logged: 12:34:17 PM

Setup failed for custom integration 'golemio': No setup or config entry setup function defined.
```
