### ISSUE TITLE
Nejde nastavit vice senzoru - neunikatni  ID golemio_next_pick_1 already exists

### ISSUE THREAD

**Issue by pschonmann** [Cmajda/ha_golemio#12]
Nejde mi nastavit vic senzoru. Dostavam hlasku viz nize, jako by se neuplatnovala nejaka promenna z nazvu v name a porad to generovalo neunikatni nazvy.
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
Integration: Sensor (documentation, issues)
First occurred: 10:21:05 PM (12 occurrences)
Last logged: 10:21:06 PM

Platform golemio does not generate unique IDs. ID golemio_next_pick_1 already exists - ignoring sensor.tridene_kontejnery_smer_metro_1_multikomoditni_sber_datum_odvozu
Platform golemio does not generate unique IDs. ID golemio_next_pick_2 already exists - ignoring sensor.tridene_kontejnery_smer_metro_2_barevne_sklo_datum_odvozu
Platform golemio does not generate unique IDs. ID golemio_next_pick_3 already exists - ignoring sensor.tridene_kontejnery_u_skolky_3_barevne_sklo_datum_odvozu
```

Konfig mam nasledujici. N00x je unikatni cislo ktery jsem nastavil podle navodu, nikoliv je nastaveni N001 :)

```YAML
sensor:
  - platform: golemio
    name: "Tříděné kontejnery"
    token: !secret golemio
    container_id: N001
  - platform: golemio
    name: "Tříděné kontejnery směr metro"
    token: !secret golemio
    container_id: N002
  - platform: golemio
    name: "Tříděné kontejnery u Metra"
    token: !secret golemio
    container_id: N003
  - platform: golemio
    name: "Tříděné kontejnery u školky"
    token: !secret golemio
    container_id: N004
```

**Comment by Cmajda** [comment]
Chyba je jen v nastavení yaml

**Comment by pschonmann** [comment]
A jak jsi ( jste ) dosel k zaveru ze yaml je spatne nastaveny ? Ten kus kodu je primo z configuration.yaml, zadny include na sensors.yaml tam neni.
Jestli bych mel postupovat podle

```yaml
 sensor: 
  - platform: golemio
    name: conc3497 # pod tímto jménem můžete dohledat požadovanou entitu (sensor.conc3497_0_papir_datum_odvozu)
    token: !secret golemio
    container_id: 3497

 - platform: golemio
   name: conc1 # pod tímto jménem můžete dohledat požadovanou entitu (sensor.conc1_4_kovy_datum_odvozu)
   token: !secret golemio
   container_id: 1
```
Tak to mi hlasi chybu intendace.
V čem je můj konfig špatně ? Můžeš(te) to prosím rozvést ?
