### ISSUE TITLE
Nejde pridat vic senzoru, yaml je ok. Part 2

### ISSUE THREAD

**Issue by pschonmann** [Cmajda/ha_golemio#13]
A jak jsi ( jste ) dosel k zaveru ze yaml je spatne nastaveny ? Ten kus kodu je primo z configuration.yaml, zadny include na sensors.yaml tam neni.
Jestli bych mel postupovat podle

```yaml
 sensor: 
  - platform: golemio
    name: conc3497 # pod tímto jménem můžete dohledat požadovanou entitu (sensor.conc3497_0_papir_datum_odvozu)
    token: !secret golemio
    container_id: 3497

 - platform: golemio
   name: conc1 # pod tímto jménem můžete dohledat požadovanou entitu (sensor.conc1_4_kovy_datum_odvozu)
   token: !secret golemio
   container_id: 1
```
Tak to mi hlasi chybu intendace.
V čem je můj konfig špatně ? Můžeš(te) to prosím rozvést ?

_Originally posted by @pschonmann in https://github.com/Cmajda/ha_golemio/issues/12#issuecomment-1924736577_
